FROM jenkins/inbound-agent:latest

USER root

RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    xz-utils \
    && rm -rf /var/lib/apt/lists/*

# Descargar Python 3.12 precompilado
RUN curl -L "https://github.com/indygreg/python-build-standalone/releases/download/20240224/cpython-3.12.2+20240224-x86_64-unknown-linux-gnu-install_only.tar.gz" \
    -o python.tar.gz \
    && tar -xzf python.tar.gz -C /usr/local --strip-components=1 \
    && rm python.tar.gz

# Symlinks
RUN ln -sf /usr/local/bin/python3.12 /usr/bin/python3 \
    && ln -sf /usr/local/bin/pip3.12 /usr/bin/pip3

# AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip && ./aws/install && rm -rf aws awscliv2.zip

# SAM CLI
RUN curl -L "https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip" -o "sam.zip" \
    && unzip sam.zip -d sam-installation && ./sam-installation/install && rm -rf sam.zip sam-installation

ENV PATH="/usr/local/bin:${PATH}"

USER jenkins